databases:
  - name: ficrec
    plan: free
    databaseName: ficrec
    user: almond

services:
  - type: web
    plan: free
    name: ficrec
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn ficrec.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ficrec
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4